package samba.domain.content;

public interface ContentProofConstants {

  int BLOCK_PROOF_HISTORICAL_HASHES_ACCUMULATOR_VECTOR_SIZE = 15;
  int EXECUTION_BLOCK_PROOF_BELLATRIX_SIZE = 11;
  int BEACON_BLOCK_PROOF_HISTORICAL_ROOTS_VECTOR_SIZE = 14;
  int EXECUTION_BLOCK_PROOF_DENEB_SIZE = 12;
  int BEACON_BLOCK_PROOF_HISTORICAL_SUMMARIES_VECTOR_SIZE = 13;
}
